name: Build STM32 Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # 2. Instalar toolchain ARM
    - name: Install ARM GCC Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make
  
    # 3. Compilar firmware
    - name: Build firmware
      run: ls -R
      # run: make (este falló)
